### POST request, RESPONSE OK
POST localhost:8080/api/account
Content-Type: application/json

{
  "FirstName": "John",
  "LastName": "Doe",
  "balance": 1.0

}

### POST request without parameters, RESPONSE NOT VALID
POST localhost:8080/api/account
Content-Type: application/json

{

}